import { IBook } from "@/library-management/types";
import { Schema } from "mongoose";


// creating a schema for book
const bookSchema: Schema<IBook> = new Schema({
    // _id: String, // auto generated by mongoDB
    title: {
        type: String,
        required: true,
        trim: true,
    },
    bookId: {
        type: String,
        required: true,
        unique: true,
        trim: true,
    },
    category: {
        type: [String],
        required: true,
    },
    authors: {
        type: [String],
        required: true,
    },
    availableCopies: {
        type: Number,
        required: true,
    },
    totalCopies: {
        type: Number,
        required: true,
    },
    borrowedBy: {
        type: [String],
        required: true,
    }
});