// creating required types
export type Email = string;
export type BookId = string;

// creating a type for user
export interface IUser {
    // _id: string,  // auto generated by mongoDB
    name: string,
    email: Email,
    password: string,
    books: {
        currentlyReading: BookId[],  // we can add the allotment time for the application (like alloted for 30 days) (if required)
        previouslyBorrowed: BookId[],
    }
}