import { BookId } from "@/library-management/types/book/book.type";

// creating required types
export type Email = string;
export type UserId = string;

export interface AllotedBook {
    bookId: BookId;
    allotmentDate: Date;
    totalAllotedDays: number;
}

// creating a type for user
export interface IUser {
    // _id: string,  // auto generated by mongoDB
    userId: UserId;
    name: string;
    email: Email;
    password: string;
    books: {
        currentlyReading: AllotedBook[],  
        previouslyBorrowed: AllotedBook[],
    },
    fine: number;
}